/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  GaugeFactory,
  GaugeFactoryInterface,
} from "../../../contracts/factories/GaugeFactory";

const _abi = [
  "function createGauge(address,address,address,address,bool,address[]) returns (address)",
  "function last_gauge() view returns (address)",
] as const;

export class GaugeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): GaugeFactoryInterface {
    return new utils.Interface(_abi) as GaugeFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GaugeFactory {
    return new Contract(address, _abi, signerOrProvider) as GaugeFactory;
  }
}
