/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface WrappedExternalBribeFactoryInterface extends utils.Interface {
  functions: {
    "createBribe(address)": FunctionFragment;
    "last_bribe()": FunctionFragment;
    "oldBribeToNew(address)": FunctionFragment;
    "voter()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createBribe"
      | "last_bribe"
      | "oldBribeToNew"
      | "voter"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createBribe",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "last_bribe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oldBribeToNew",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "voter", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createBribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "last_bribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oldBribeToNew",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voter", data: BytesLike): Result;

  events: {};
}

export interface WrappedExternalBribeFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WrappedExternalBribeFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createBribe(
      existing_bribe: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    last_bribe(overrides?: CallOverrides): Promise<[string]>;

    oldBribeToNew(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    voter(overrides?: CallOverrides): Promise<[string]>;
  };

  createBribe(
    existing_bribe: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  last_bribe(overrides?: CallOverrides): Promise<string>;

  oldBribeToNew(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  voter(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createBribe(
      existing_bribe: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    last_bribe(overrides?: CallOverrides): Promise<string>;

    oldBribeToNew(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    voter(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createBribe(
      existing_bribe: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    last_bribe(overrides?: CallOverrides): Promise<BigNumber>;

    oldBribeToNew(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    voter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createBribe(
      existing_bribe: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    last_bribe(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oldBribeToNew(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    voter(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
