/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface BribeFactoryInterface extends utils.Interface {
  functions: {
    "createExternalBribe(address[])": FunctionFragment;
    "createInternalBribe(address[])": FunctionFragment;
    "last_external_bribe()": FunctionFragment;
    "last_internal_bribe()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createExternalBribe"
      | "createInternalBribe"
      | "last_external_bribe"
      | "last_internal_bribe"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createExternalBribe",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createInternalBribe",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "last_external_bribe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "last_internal_bribe",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createExternalBribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createInternalBribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "last_external_bribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "last_internal_bribe",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BribeFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BribeFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createExternalBribe(
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createInternalBribe(
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    last_external_bribe(overrides?: CallOverrides): Promise<[string]>;

    last_internal_bribe(overrides?: CallOverrides): Promise<[string]>;
  };

  createExternalBribe(
    allowedRewards: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createInternalBribe(
    allowedRewards: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  last_external_bribe(overrides?: CallOverrides): Promise<string>;

  last_internal_bribe(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createExternalBribe(
      allowedRewards: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<string>;

    createInternalBribe(
      allowedRewards: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<string>;

    last_external_bribe(overrides?: CallOverrides): Promise<string>;

    last_internal_bribe(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createExternalBribe(
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createInternalBribe(
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    last_external_bribe(overrides?: CallOverrides): Promise<BigNumber>;

    last_internal_bribe(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createExternalBribe(
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createInternalBribe(
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    last_external_bribe(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    last_internal_bribe(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
