/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface GaugeFactoryInterface extends utils.Interface {
  functions: {
    "createGauge(address,address,address,address,bool,address[])": FunctionFragment;
    "last_gauge()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "createGauge" | "last_gauge"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createGauge",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "last_gauge",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createGauge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "last_gauge", data: BytesLike): Result;

  events: {};
}

export interface GaugeFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GaugeFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createGauge(
      _pool: PromiseOrValue<string>,
      _internal_bribe: PromiseOrValue<string>,
      _external_bribe: PromiseOrValue<string>,
      _ve: PromiseOrValue<string>,
      isPair: PromiseOrValue<boolean>,
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    last_gauge(overrides?: CallOverrides): Promise<[string]>;
  };

  createGauge(
    _pool: PromiseOrValue<string>,
    _internal_bribe: PromiseOrValue<string>,
    _external_bribe: PromiseOrValue<string>,
    _ve: PromiseOrValue<string>,
    isPair: PromiseOrValue<boolean>,
    allowedRewards: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  last_gauge(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createGauge(
      _pool: PromiseOrValue<string>,
      _internal_bribe: PromiseOrValue<string>,
      _external_bribe: PromiseOrValue<string>,
      _ve: PromiseOrValue<string>,
      isPair: PromiseOrValue<boolean>,
      allowedRewards: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<string>;

    last_gauge(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createGauge(
      _pool: PromiseOrValue<string>,
      _internal_bribe: PromiseOrValue<string>,
      _external_bribe: PromiseOrValue<string>,
      _ve: PromiseOrValue<string>,
      isPair: PromiseOrValue<boolean>,
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    last_gauge(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createGauge(
      _pool: PromiseOrValue<string>,
      _internal_bribe: PromiseOrValue<string>,
      _external_bribe: PromiseOrValue<string>,
      _ve: PromiseOrValue<string>,
      isPair: PromiseOrValue<boolean>,
      allowedRewards: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    last_gauge(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
