/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBribe,
  IBribeInterface,
} from "../../../contracts/interfaces/IBribe";

const _abi = [
  "function _deposit(uint256,uint256)",
  "function _withdraw(uint256,uint256)",
  "function getRewardForOwner(uint256,address[])",
  "function left(address) view returns (uint256)",
  "function notifyRewardAmount(address,uint256)",
] as const;

export class IBribe__factory {
  static readonly abi = _abi;
  static createInterface(): IBribeInterface {
    return new utils.Interface(_abi) as IBribeInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IBribe {
    return new Contract(address, _abi, signerOrProvider) as IBribe;
  }
}
