/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGauge,
  IGaugeInterface,
} from "../../../contracts/interfaces/IGauge";

const _abi = [
  "function claimFees() returns (uint256, uint256)",
  "function getReward(address,address[])",
  "function isForPair() view returns (bool)",
  "function left(address) view returns (uint256)",
  "function notifyRewardAmount(address,uint256)",
] as const;

export class IGauge__factory {
  static readonly abi = _abi;
  static createInterface(): IGaugeInterface {
    return new utils.Interface(_abi) as IGaugeInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IGauge {
    return new Contract(address, _abi, signerOrProvider) as IGauge;
  }
}
