/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGaugeFactory,
  IGaugeFactoryInterface,
} from "../../../contracts/interfaces/IGaugeFactory";

const _abi = [
  "function createGauge(address,address,address,address,bool,address[]) returns (address)",
] as const;

export class IGaugeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IGaugeFactoryInterface {
    return new utils.Interface(_abi) as IGaugeFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGaugeFactory {
    return new Contract(address, _abi, signerOrProvider) as IGaugeFactory;
  }
}
