/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPairCallee,
  IPairCalleeInterface,
} from "../../../contracts/interfaces/IPairCallee";

const _abi = ["function hook(address,uint256,uint256,bytes)"] as const;

export class IPairCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IPairCalleeInterface {
    return new utils.Interface(_abi) as IPairCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPairCallee {
    return new Contract(address, _abi, signerOrProvider) as IPairCallee;
  }
}
