/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPairFactory,
  IPairFactoryInterface,
} from "../../../contracts/interfaces/IPairFactory";

const _abi = [
  "function allPairsLength() view returns (uint256)",
  "function createPair(address,address,bool) returns (address)",
  "function getPair(address,address,bool) view returns (address)",
  "function isPair(address) view returns (bool)",
  "function pairCodeHash() pure returns (bytes32)",
] as const;

export class IPairFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPairFactoryInterface {
    return new utils.Interface(_abi) as IPairFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPairFactory {
    return new Contract(address, _abi, signerOrProvider) as IPairFactory;
  }
}
