/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVeArtProxy,
  IVeArtProxyInterface,
} from "../../../contracts/interfaces/IVeArtProxy";

const _abi = [
  "function _tokenURI(uint256,uint256,uint256,uint256) pure returns (string)",
] as const;

export class IVeArtProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IVeArtProxyInterface {
    return new utils.Interface(_abi) as IVeArtProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVeArtProxy {
    return new Contract(address, _abi, signerOrProvider) as IVeArtProxy;
  }
}
