/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVoter,
  IVoterInterface,
} from "../../../contracts/interfaces/IVoter";

const _abi = [
  "function _ve() view returns (address)",
  "function attachTokenToGauge(uint256,address)",
  "function detachTokenFromGauge(uint256,address)",
  "function distribute(address)",
  "function emergencyCouncil() view returns (address)",
  "function emitDeposit(uint256,address,uint256)",
  "function emitWithdraw(uint256,address,uint256)",
  "function governor() view returns (address)",
  "function isWhitelisted(address) view returns (bool)",
  "function notifyRewardAmount(uint256)",
] as const;

export class IVoter__factory {
  static readonly abi = _abi;
  static createInterface(): IVoterInterface {
    return new utils.Interface(_abi) as IVoterInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IVoter {
    return new Contract(address, _abi, signerOrProvider) as IVoter;
  }
}
