/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { PairFees, PairFeesInterface } from "../../contracts/PairFees";

const _abi = [
  "constructor(address,address)",
  "function claimFeesFor(address,uint256,uint256)",
] as const;

export class PairFees__factory {
  static readonly abi = _abi;
  static createInterface(): PairFeesInterface {
    return new utils.Interface(_abi) as PairFeesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PairFees {
    return new Contract(address, _abi, signerOrProvider) as PairFees;
  }
}
