/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VeArtProxy,
  VeArtProxyInterface,
} from "../../contracts/VeArtProxy";

const _abi = [
  "function _tokenURI(uint256,uint256,uint256,uint256) pure returns (string)",
] as const;

export class VeArtProxy__factory {
  static readonly abi = _abi;
  static createInterface(): VeArtProxyInterface {
    return new utils.Interface(_abi) as VeArtProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VeArtProxy {
    return new Contract(address, _abi, signerOrProvider) as VeArtProxy;
  }
}
