/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Velo, VeloInterface } from "../../contracts/Velo";

const _abi = [
  "constructor()",
  "event Approval(address indexed,address indexed,uint256)",
  "event Transfer(address indexed,address indexed,uint256)",
  "function allowance(address,address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function balanceOf(address) view returns (uint256)",
  "function decimals() view returns (uint8)",
  "function initialMint(address)",
  "function initialMinted() view returns (bool)",
  "function merkleClaim() view returns (address)",
  "function mint(address,uint256) returns (bool)",
  "function minter() view returns (address)",
  "function name() view returns (string)",
  "function redemptionReceiver() view returns (address)",
  "function setMinter(address)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address,uint256) returns (bool)",
  "function transferFrom(address,address,uint256) returns (bool)",
] as const;

export class Velo__factory {
  static readonly abi = _abi;
  static createInterface(): VeloInterface {
    return new utils.Interface(_abi) as VeloInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Velo {
    return new Contract(address, _abi, signerOrProvider) as Velo;
  }
}
