/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as factories from "./factories";
export type { factories };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ExternalBribe } from "./ExternalBribe";
export type { Gauge } from "./Gauge";
export type { InternalBribe } from "./InternalBribe";
export type { Minter } from "./Minter";
export type { Pair } from "./Pair";
export type { PairFees } from "./PairFees";
export type { RewardsDistributor } from "./RewardsDistributor";
export type { VeArtProxy } from "./VeArtProxy";
export type { Velo } from "./Velo";
export type { Voter } from "./Voter";
export type { VotingEscrow } from "./VotingEscrow";
export type { WrappedExternalBribe } from "./WrappedExternalBribe";
