/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { Multicall } from "./Multicall";
export type { Ownable } from "./Ownable";
export type { SelfPermit } from "./SelfPermit";
