/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { PairFees, PairFeesInterface } from "../PairFees";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "_token1",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
    ],
    name: "claimFeesFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class PairFees__factory {
  static readonly abi = _abi;
  static createInterface(): PairFeesInterface {
    return new utils.Interface(_abi) as PairFeesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PairFees {
    return new Contract(address, _abi, signerOrProvider) as PairFees;
  }
}
