/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { VeArtProxy, VeArtProxyInterface } from "../VeArtProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_balanceOf",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_locked_end",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "_tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "output",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class VeArtProxy__factory {
  static readonly abi = _abi;
  static createInterface(): VeArtProxyInterface {
    return new utils.Interface(_abi) as VeArtProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VeArtProxy {
    return new Contract(address, _abi, signerOrProvider) as VeArtProxy;
  }
}
